In [1]:
library(ipumsr)
library(dplyr)
library(survey)
library(srvyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: grid

Loading required package: Matrix

Loading required package: survival


Attaching package: ‘survey’


The following object is masked from ‘package:graphics’:

    dotchart



Attaching package: ‘srvyr’


The following object is masked from ‘package:stats’:

    filter

In [2]:
#ddi <- read_ipums_ddi("usa_00064.xml")
data <- read_ipums_micro(data_file = "usa_00064.dat", ddi = "usa_00064.xml")

Use of data from IPUMS USA is subject to conditions including that users should cite the data appropriately. Use command `ipums_conditions()` for more details.

In [3]:
#Reno <- read.csv(file='usa_00063.csv', header=TRUE)
#head(data)

In [4]:
data <- data %>% filter(METAREA==672 | MET2013==39900)

In [5]:
head (data)

  YEAR SAMPLE SERIAL  CBSERIAL HHWT CLUSTER      METAREA METAREAD MET2013
1 1960 196002 1649447 NA       20   1.960016e+12 672     6720     NA
2 1960 196002 1649447 NA       20   1.960016e+12 672     6720     NA
3 1960 196002 1649447 NA       20   1.960016e+12 672     6720     NA
4 1960 196002 1649447 NA       20   1.960016e+12 672     6720     NA
5 1960 196002 1649447 NA       20   1.960016e+12 672     6720     NA
6 1960 196002 1649448 NA       20   1.960016e+12 672     6720     NA
  STRATA ⋯ MARST RACE RACED HISPAN HISPAND BPL BPLD OCC1950 IND1950 OCCSCORE
1 NA     ⋯ 1     1    100   0      0       20  2000 595     916     11
2 NA     ⋯ 1     1    100   0      0       27  2700 390     646     25
3 NA     ⋯ 6     1    100   0      0        6   600 999       0      0
4 NA     ⋯ 6     1    100   0      0        6   600 999       0      0
5 NA     ⋯ 6     1    100   0      0       32  3200 999       0      0
6 NA     ⋯ 1     1    100   0      0       29  2900 290     846     42

In [6]:
ipums_val_labels(data$RACE)
#ipums_var_label(data$RACE)
#ipums_var_info(data$RACE)

  val lbl
1 1   White
2 2   Black/African American
3 3   American Indian or Alaska Native
4 4   Chinese
5 5   Japanese
6 6   Other Asian or Pacific Islander
7 7   Other race, nec
8 8   Two major races
9 9   Three or more major races

In [ ]:
#lbl_na_if()
#lbl_clean()
#as_factor()
#zap_labels()
#zap_ipums_attributes()

In [8]:
#save(Reno_clean, file="Reno.RData")
saveRDS(data, file = "Reno.rds")