In [1]:
library(ipumsr)
library(dplyr)
library(survey)
library(srvyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

ERROR: Error in library(survey): there is no package called ‘survey’

In [2]:
#ddi <- read_ipums_ddi("usa_00064.xml")
data <- read_ipums_micro(data_file = "usa_00064.dat", ddi = "usa_00064.xml")

ERROR: Error in `custom_check_file_exists()`:
! Could not find file `/home/jcolo/project/LTCC_Reno/usa_00064.dat`.
ℹ Use `data_file` to specify the path to the data file associated with the provided `ddi`.

In [3]:
#Reno <- read.csv(file='usa_00063.csv', header=TRUE)
#head(data)

In [4]:
data <- data %>% filter(METAREA==672 | MET2013==39900)

ERROR: Error in UseMethod("filter"): no applicable method for 'filter' applied to an object of class "function"

In [ ]:
df[!complete.cases(df),]

In [5]:
data %>% group_by(RACE=haven::as_factor(RACE)) %>% summarize(n=sum(PERWT)) %>% mutate(pct = n/sum(n))

  RACE                             n       pct
1 White                            1492046 0.772383283
2 Black/African American             48610 0.025163803
3 American Indian or Alaska Native   32982 0.017073700
4 Chinese                            18236 0.009440179
5 Japanese                            7179 0.003716333
6 Other Asian or Pacific Islander    79037 0.040914863
7 Other race, nec                   128182 0.066355618
8 Two major races                   115287 0.059680299
9 Three or more major races          10184 0.005271923

In [6]:
#ipums_val_labels(data$RACE)
#ipums_var_label(data$RACE)
#ipums_var_info(data$RACE)

In [7]:
#lbl_na_if()
#lbl_clean()
#as_factor()
#zap_labels()
#zap_ipums_attributes()

In [8]:
data %>% group_by(HISPAN=haven::as_factor(HISPAN)) %>% summarize(n=sum(PERWT)) %>% mutate(pct = n/sum(n))

  HISPAN       n       pct
1 Not Hispanic 1545756 0.800187188
2 Mexican       298877 0.154718821
3 Puerto Rican    8761 0.004535282
4 Cuban           3316 0.001716584
5 Other          75033 0.038842123

Recode using dplyr (Tidyverse according to rpubs.com)

In [13]:
data <- data %>%
    mutate(RACEETH = case_when(
        RACE >6 & RACE <=9 ~ "Other",
        HISPAN >1 & HISPAN <5 ~ "Latino",
        RACE == 1 ~ "White",
        RACE == 2 ~ "Black",
        RACE == 3 ~ "American Indian",
        RACE >3 & RACE <7 ~ "Asian"
        ))

In [15]:
data %>% group_by (RACEETH) %>% summarize(n=sum(PERWT)) %>% mutate(pct= n/sum(n))

  RACEETH         n       pct
1 American Indian   30922 0.01600731
2 Asian            103448 0.05355164
3 Black             47308 0.02448980
4 Latino            44112 0.02283534
5 Other            253653 0.13130784
6 White           1452300 0.75180808

In [16]:
summary(data)

      YEAR          SAMPLE           SERIAL           CBSERIAL
 Min.   :1960   Min.   :196002   Min.   : 313446   Min.   :2.396e+03
 1st Qu.:1980   1st Qu.:198002   1st Qu.: 763358   1st Qu.:1.228e+06
 Median :2010   Median :201001   Median : 779439   Median :2.019e+12
 Mean   :2001   Mean   :200151   Mean   : 898832   Mean   :1.439e+12
 3rd Qu.:2019   3rd Qu.:201901   3rd Qu.: 831444   3rd Qu.:2.024e+12
 Max.   :2024   Max.   :202401   Max.   :1652697   Max.   :2.024e+12
                                                   NA's   :8541
      HHWT           CLUSTER             METAREA         METAREAD
 Min.   :  0.00   Min.   :1.960e+12   Min.   :672     Min.   :6720
 1st Qu.: 45.00   1st Qu.:1.980e+12   1st Qu.:672     1st Qu.:6720
 Median : 71.00   Median :2.010e+12   Median :672     Median :6720
 Mean   : 83.67   Mean   :2.002e+12   Mean   :672     Mean   :6720
 3rd Qu.:100.00   3rd Qu.:2.019e+12   3rd Qu.:672     3rd Qu.:6720
 Max.   :699.00   Max.   :2.024e+12   Max.   :672     Max.   :6720
                                      NA's   :10328   NA's   :10328
    MET2013          STRATA            GQ            PERNUM
 Min.   :39900   Min.   :    4   Min.   :1.000   Min.   : 1.000
 1st Qu.:39900   1st Qu.:10032   1st Qu.:1.000   1st Qu.: 1.000
 Median :39900   Median :10132   Median :1.000   Median : 2.000
 Mean   :39900   Mean   : 8977   Mean   :1.062   Mean   : 2.126
 3rd Qu.:39900   3rd Qu.:10332   3rd Qu.:1.000   3rd Qu.: 3.000
 Max.   :39900   Max.   :20032   Max.   :5.000   Max.   :18.000
 NA's   :8541    NA's   :4235
     PERWT             SEX             AGE            MARST
 Min.   :  5.00   Min.   :1.000   Min.   : 0.00   Min.   :1.000
 1st Qu.: 45.00   1st Qu.:1.000   1st Qu.:19.00   1st Qu.:1.000
 Median : 71.00   Median :1.000   Median :37.00   Median :4.000
 Mean   : 83.81   Mean   :1.499   Mean   :38.26   Mean   :3.537
 3rd Qu.:100.00   3rd Qu.:2.000   3rd Qu.:57.00   3rd Qu.:6.000
 Max.   :700.00   Max.   :2.000   Max.   :93.00   Max.   :6.000

      RACE           RACED           HISPAN         HISPAND
 Min.   :1.000   Min.   :100.0   Min.   :0.000   Min.   :  0.00
 1st Qu.:1.000   1st Qu.:100.0   1st Qu.:0.000   1st Qu.:  0.00
 Median :1.000   Median :100.0   Median :0.000   Median :  0.00
 Mean   :1.884   Mean   :200.1   Mean   :0.234   Mean   : 24.76
 3rd Qu.:1.000   3rd Qu.:177.0   3rd Qu.:0.000   3rd Qu.:  0.00
 Max.   :9.000   Max.   :985.0   Max.   :4.000   Max.   :499.00

      BPL              BPLD          OCC1950         IND1950
 Min.   :  1.00   Min.   :  100   Min.   :  0.0   Min.   :  0.0
 1st Qu.:  6.00   1st Qu.:  600   1st Qu.:320.0   1st Qu.:  0.0
 Median : 32.00   Median : 3200   Median :731.0   Median :578.0
 Mean   : 64.34   Mean   : 6434   Mean   :645.4   Mean   :445.1
 3rd Qu.: 39.00   3rd Qu.: 3900   3rd Qu.:999.0   3rd Qu.:836.0
 Max.   :950.00   Max.   :95000   Max.   :999.0   Max.   :998.0

    OCCSCORE       RACEETH
 Min.   : 0.00   Length:23049
 1st Qu.: 0.00   Class :character
 Median :19.00   Mode  :character
 Mean   :16.97
 3rd Qu.:27.00
 Max.   :80.00

In [8]:
#save(Reno_clean, file="Reno.RData")
saveRDS(data, file = "Reno.rds")